app_blog/urls.py
from django.urls import path
from app_blog  import views

app_name = 'app_blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('create/', views.CreateBlog.as_view(), name='create'),
    path('update/<pk>/', views.UpdateBlog.as_view(), name='update'),
    path('manage/', views.MyBlog.as_view(), name='manage'),
    path('delete/<pk>/', views.delete_blog, name='delete'),
    path('blog/<slug:slug>/', views.single_blog, name='blog'),
    path('like/<pk>/', views.like_blog, name='like'),
    path('dislike/<pk>/', views.dislike_blog, name='dislike'),
]

app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.profile_update, name='update'),
    path('extra/', views.profile_extra, name='extra'),
    path('modify/', views.profile_extra_update, name='modify'),
    path('password/', views.password_change, name='password'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

app_login/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='user_profile', on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='avatars')
    bio = models.TextField(verbose_name='Bio')
    location = models.CharField(max_length=20)
    def __str__(self):
        return self.user.username

app_login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import fields
from app_login.models import UserProfile

class SignUpForm(UserCreationForm):
    email = forms.CharField(required=True)
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class ProfileUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar','bio','location')

app_login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from app_login.forms import SignUpForm, ProfileUpdateForm, UserProfileForm
from django.contrib.auth import login as user_login, authenticate, logout as user_logout
from django.contrib.auth.decorators import login_required
from django.http.response import HttpResponseRedirect
from django.urls import reverse

def signup(request):
    form = SignUpForm()
    registerd = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            form.save()
            registerd = True
    context={'form':form,'registerd':registerd}
    return render(request, 'app_login/signup.html', context)

def login(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username,password=password)
            if user is not None:
                user_login(request, user)
                return HttpResponseRedirect(reverse('app_blog:blogs'))
    context={'form':form}
    return render(request, 'app_login/login.html', context)

@login_required
def logout(request):
    user_logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):
    context={}
    return render(request, 'app_login/profile.html', context)

@login_required
def profile_update(request):
    current_user = request.user
    form = ProfileUpdateForm(instance=current_user)
    if request.method == 'POST':
        form = ProfileUpdateForm(data=request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
            # form = ProfileUpdateForm(instance=current_user)
    context={'form':form,}
    return render(request, 'app_login/profile_update.html', context)

@login_required
def profile_extra(request):
    form = UserProfileForm()
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    context={'form':form, 'action':'Add'}
    return render(request, 'app_login/profile_extra.html', context)

@login_required
def profile_extra_update(request):
    form = UserProfileForm(instance=request.user.user_profile)
    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES, instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('app_login:profile'))
    context={'form':form, 'action':'Update'}
    return render(request, 'app_login/profile_extra.html', context)

@login_required
def password_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    context={'form':form,'changed':changed}
    return render(request, 'app_login/password_change.html', context)

templates/app_login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Log In{% endblock  %}

{% block body_block %}

<div class="container m-auto w-50">
    <div class="card p-5">
        <h2>Login to Account</h2>
        <p class='lead'>Insert correct credentials to log into account</p>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="Log In">
        </form>
        <br>
        <p>Don't have Account? <a href="{% url 'app_login:signup' %}">Sign Up</a></p>
    </div>
</div>

{% endblock  %}

templates/app_login/password_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Update Password{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
{% if changed %}
    <div class="alert alert-success" role="alert">
        Password Updated Successfully! Go to <a href="{% url 'app_login:login' %}">Log In</a>
    </div>
{% else %}
    <div class="card p-5 mb-5">
        <h2>Update Password</h2>
        <p class='lead'>Insert correct credentials to create an account</p>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="Change Password">
            <a class="btn btn-info mt-3" href="{% url 'app_login:profile' %}">Cancel</a>
        </form>
    </div>
{% endif %}
</div>
{% endblock  %}

templates/app_login/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title_block %}{{user.username|capfirst}}'s Profile{% endblock  %}
{% block body_block %}
<div class="container m-auto">
    <div class="row">
        <div class="col-md-4 bg-dark text-light rounded-start">
            <div class="rounded mt-3 position-relative overflow-hidden" style="max-height:356px;">
                <img class="img-fluid w-100"
                {% if user.user_profile %}
                    src="/media/{{user.user_profile.avatar}}" 
                {% else %}
                    src="{% static 'images/default.png' %}"
                {% endif %}
                alt="">
                <a class="position-absolute m-2 bottom-0 end-0 btn btn-sm btn-outline-dark">View</a>
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between">
                    <h4 class="card-title d-inline">
                    {% if user.first_name and user.last_name %}
                        {{user.first_name}} {{user.last_name}}
                    {% else %}
                        Update Names
                    {% endif %}
                    </h4>
                    <p class="card-text d-inline text-light">
                    <i class="bi bi-person-circle"></i> /{{user.username}}</p>
                </div>
                <p class="card-text text-light lead mb-0">
                <i class="bi bi-envelope-fill"></i>
                {{user.email}}</p>
                <p class="card-text text-light lead">
                <i class="bi bi-calendar3"></i>
                {{user.date_joined|date}}</p>
                <div class="input-group input-group-sm">
                    <span class="input-group-text bg-light" ><b>Edit:</b></span>
                    <a {% if user.user_profile %}
                        href="{% url 'app_login:modify' %}"
                    {% else %}
                        href="{% url 'app_login:extra' %}"
                    {% endif %} class="btn btn-success">
                        <i class="bi bi-pencil-square"></i> Profile</a>
                    <a class="btn btn-primary" href="{% url 'app_login:update' %}">
                        <i class="bi bi-file-person"></i> Account</a>
                    <a class="btn btn-danger" href="{% url 'app_login:password' %}">
                        <i class="bi bi-shield-check"></i> Password</a>
                </div>
            </div>
        </div>
        <div class="col-md-8 bg-light p-5 border border-2 border-dark rounded-end">
            <h5 class="display-5">{{user.username|capfirst}}'s Profile</h5>
            <div class="card p-3 lead">{{user.user_profile.bio|default:"Add Bio"}}</div>
            <div class=" container mt-2 d-flex justify-content-between flex-wrap">
                <p class="lead d-inline"><kbd>
                    <i class="bi bi-geo-alt-fill"></i></kbd> 
                    {{user.user_profile.location|default:"Add Location"}}</p>
                <p class="lead d-inline"><kbd>
                    <i class="bi bi-check-circle-fill"></i></kbd> 
                    {{user.last_login|date:'f A l, F j'}}</p>
            </div>
            <div class="card">
                <div class="card-header d-flex justify-content-between">
                    <h5>My Blogs:</h5>
                    <a href="{% url 'app_blog:manage' %}" class="btn btn-warning btn-sm">Manage Blogs</a>
                </div>
                <div class="card-body">
                    <ul>
                    {% for blog in user.blog_author.all %}
                        <li><a class="text-decoration-none" href="{% url 'app_blog:blog' slug=blog.slug %}">{{blog.title}}</a></li>
                    {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock  %}

templates/app_login/profile_extra.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}{{action}} Profile{% endblock  %}
{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5">
        <h2>{{action}} to Profile</h2>
        <p class='lead'>Insert Profile Photo, Bio and Location</p>
        <form method="post" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="{{action}} Data">
            <a class="btn btn-info mt-3" href="{% url 'app_login:profile' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock  %}

templates/app_login/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Update Account{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5 mb-5">
        <h2>Update Account</h2>
        <p class='lead'>Insert correct credentials to update account</p>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="Update Profile">
            <a class="btn btn-info mt-3" href="{% url 'app_login:profile' %}">Cancel</a>
        </form>
    </div>
</div>
{% endblock  %}

templates/app_login/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Sign Up{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
{% if registerd %}
    <div class="alert alert-success" role="alert">
        Registration Completed Successfully! <a href="{% url 'app_login:login' %}">Login</a>
    </div>
{% else %}
    <div class="card p-5 mb-5">
        <h2>Create Account</h2>
        <p class='lead'>Insert correct credentials to create an account</p>
        <form method="post">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="Create Account">
        </form>
        <br>
        <p>Already have Account? <a href="{% url 'app_login:login' %}">Login</a></p>
    </div>
{% endif %}
</div>
{% endblock  %}