app_blog/urls.py
from django.urls import path
from app_blog  import views

app_name = 'app_blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('create/', views.CreateBlog.as_view(), name='create'),
    path('update/<pk>/', views.UpdateBlog.as_view(), name='update'),
    path('manage/', views.MyBlog.as_view(), name='manage'),
    path('delete/<pk>/', views.delete_blog, name='delete'),
    path('blog/<slug:slug>/', views.single_blog, name='blog'),
    path('like/<pk>/', views.like_blog, name='like'),
    path('dislike/<pk>/', views.dislike_blog, name='dislike'),
]

app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.profile_update, name='update'),
    path('extra/', views.profile_extra, name='extra'),
    path('modify/', views.profile_extra_update, name='modify'),
    path('password/', views.password_change, name='password'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <title>{% block title_block %}{% endblock  %}</title>
</head>
<body>
    <header class="app-header mb-2 pt-2">
        <nav class="navbar navbar-light">
            <div class="container">
                <a class="navbar-brand" href="{% url 'index' %}"><img draggable="false" src="{% static 'images/logo.svg' %}" alt=""></a>
                <form class="justify-content-start"> 
                    {% if user.is_authenticated %}
                    <a href="{% url 'app_blog:create' %}" class="btn btn-outline-primary" type="button">Create Blog</a>
                    <a href="{% url 'app_login:profile' %}" class="btn btn-outline-dark" type="button">{{user.username}}</a>
                    <a href="{% url 'app_login:logout' %}" class="btn btn-dark" type="button">Log Out</a>
                    {% else %}
                    <a href="{% url 'app_login:login' %}" class="btn btn-outline-dark" type="button">Log In</a>
                    <a href="{% url 'app_login:signup' %}" class="btn btn-dark text-light" type="button">Sign Up</a>
                    {% endif %} 
                </form>
              </div>
        </nav>
    </header>
    {% block body_block %}
    {% endblock  %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>