app_blog/urls.py
from django.urls import path
from app_blog  import views

app_name = 'app_blog'

urlpatterns = [
    path('', views.BlogList.as_view(), name='blogs'),
    path('create/', views.CreateBlog.as_view(), name='create'),
    path('update/<pk>/', views.UpdateBlog.as_view(), name='update'),
    path('manage/', views.MyBlog.as_view(), name='manage'),
    path('delete/<pk>/', views.delete_blog, name='delete'),
    path('blog/<slug:slug>/', views.single_blog, name='blog'),
    path('like/<pk>/', views.like_blog, name='like'),
    path('dislike/<pk>/', views.dislike_blog, name='dislike'),
]

app_login/urls.py
from django.urls import path
from . import views

app_name = 'app_login'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('update/', views.profile_update, name='update'),
    path('extra/', views.profile_extra, name='extra'),
    path('modify/', views.profile_extra_update, name='modify'),
    path('password/', views.password_change, name='password'),
]

blog_project/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('app_login.urls')),
    path('blogs/', include('app_blog.urls')),
    path('', views.index, name='index')
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

app_blog/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_author')
    title = models.CharField(max_length=150, verbose_name='Insert Title')
    sub_title = models.CharField(max_length=264, verbose_name='Insert Sub-title', default='')
    slug = models.SlugField(max_length=264, unique=True)
    content = models.TextField(verbose_name='Blog Content')
    image = models.ImageField(upload_to='blogs', verbose_name='Image')
    published = models.DateTimeField(auto_now_add=True)
    edited = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ['-published',]
    def __str__(self):
        return self.title

class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_comment')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    comment = models.TextField(verbose_name='Blog Comment', default='')
    commented = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ('-commented',)
    def __str__(self):
        return self.comment

class Like(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='blog_like')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_like')
    def __str__(self):
        return self.user+' likes '+self.blog

app_blog/forms.py
from django import forms
from django.forms import fields, widgets
from app_blog.models import Blog, Comment


class CommentForm(forms.ModelForm):
    comment = forms.CharField(label="", widget=forms.Textarea(attrs={'rows':'1',}))
    class Meta:
        model = Comment
        fields = ('comment',)

app_blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, UpdateView, ListView
from django.views.generic.base import TemplateView
from app_blog.models import Blog, Like
from uuid import uuid4
from app_blog.forms import CommentForm
from slugify import slugify


class CreateBlog(LoginRequiredMixin, CreateView):
    model = Blog
    template_name = 'app_blog/create_blog.html'
    fields = ('title','sub_title','content','image')
    def form_valid(self, form):
        blog_obj = form.save(commit=False)
        blog_obj.author = self.request.user
        blog_obj.image = self.request.FILES['image']
        blog_obj.slug = slugify(blog_obj.title)+'-'+str(uuid4())
        blog_obj.save()
        return HttpResponseRedirect(reverse('app_blog:blogs'))

class UpdateBlog(LoginRequiredMixin, UpdateView):
    model = Blog
    template_name = 'app_blog/edit_blog.html'
    fields = ('title','sub_title','content','image')
    def get_success_url(self, **kwargs):
        return reverse_lazy('app_blog:blog', kwargs={'slug':self.object.slug})

class MyBlog(LoginRequiredMixin, TemplateView):
    template_name = 'app_blog/my_blogs.html'

class BlogList(ListView):
    context_object_name = 'blogs'
    model = Blog
    template_name = 'app_blog/all_blogs.html'
    # queryset = Blog.objects.order_by('-published')

def single_blog(request, slug):
    blog = Blog.objects.get(slug=slug)
    comment_form = CommentForm()
    liked=False
    if request.user.is_authenticated:
        already_liked = Like.objects.filter(blog=blog, user=request.user)
        if already_liked:
            liked=True
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.user = request.user
            comment.blog = blog
            comment.save()
            return HttpResponseRedirect(reverse('app_blog:blog', kwargs={'slug':slug}))
    context={'blog':blog, 'comment_form':comment_form, 'liked':liked}
    return render(request, 'app_blog/single_blog.html', context)

@login_required
def like_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    if not already_liked:
        liked = Like(blog=blog, user=user)
        liked.save()
    return HttpResponseRedirect(reverse('app_blog:blog', kwargs={'slug':blog.slug}))

@login_required
def dislike_blog(request, pk):
    blog = Blog.objects.get(pk=pk)
    user = request.user
    already_liked = Like.objects.filter(blog=blog, user=user)
    already_liked.delete()
    return HttpResponseRedirect(reverse('app_blog:blog', kwargs={'slug':blog.slug}))

@login_required
def delete_blog(request,pk):
    blog = Blog.objects.get(pk=pk)
    msg = 'Failed'
    if blog.author:
        if request.user == blog.author:
            blog.delete()
            msg = 'Success'
    context={'msg':msg}
    return render(request, 'app_blog/confirm.html', context)

templates/app_blog/all_blogs.html
{% extends 'base.html' %}
{% block title_block %}All Blogs{% endblock  %}
{% load custom_filters %}
{% load static %}
{% block body_block %}
<main class="blog-grid-page">
    <div class="container">
        <p class='lead'>Newly Posted Blogs For You</p>
        <div class="row mt-2">
            
            {% for blog in blogs %}
            <div class="col-md-4 mb-4">
                <div class="card" style="height:355px">
                    <div class="overflow-hidden" style="height:200px">
                        <a href="{% url 'app_blog:blog' slug=blog.slug %}">
                        <img class="img-fluid"
                            {% if blog.blog_image == "" %}
                                src="{% static '/images/empty.jpg' %}"
                            {% else %}
                                src="/media/{{blog.image}}"
                            {% endif %} 
                        alt=""></a>
                    </div>
                    <div class="px-3 py-1">
                        <p class="d-flex justify-content-between mb-1 text-secondary">
                            <span><i class="bi bi-calendar3"></i> {{blog.published|date}}</span>
                            <span><i class="bi bi-person-circle"></i> {{blog.author}}</span>
                        </p>
                        <h5>{{blog.title|value_range:60}}</h5>
                        <p class="mb-0">{{blog.content|value_range:85}}</p>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>
        <div class="row">
            <div class="col-12 pb-5 mb-5">
                    <nav class="d-flex align-items-center justify-content-center my-4">
                        <a class="btn btn-light mx-1" href="#">&larr;</a>
                        <a class="btn btn-light mx-1" href="#">01</a>
                        <a class="btn btn-light mx-1" href="#">02</a>
                        <a class="btn btn-light mx-1" href="#">03</a>
                        <a class="btn btn-light mx-1" href="#">&rarr;</a>
                    </nav>
            </div>
        </div>
    </div>
</main>

{% endblock  %}

templates/app_blog/confirm.html
{% extends 'base.html' %}
{% block title_block %}My Blog{% endblock  %}
{% load static %}
{% block body_block %}
<div class="container">
{% if user.is_authenticated %}
    {% if msg %}
    <div class="alert alert-warning">{{msg}}</div>
    {% endif %}
{% else %}
    <h4>Sorry!</h4>
    <p>You are not allowed to use this!</p>
{% endif %}
</div>
{% endblock  %}

templates/app_blog/create_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Create Blog{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5 mb-5">
        <h2>Create Blog</h2>
        <p class="text-secondary">Insert informations and publish your blog.</p>
        <form method="post" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="Post Blog">
        </form>
    </div>
</div>
{% endblock  %}

templates/app_blog/edit_blog.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %}Edit Blog{% endblock  %}

{% block body_block %}
<div class="container m-auto w-50">
    <div class="card p-5 mb-5">
        {% if blog.author == user %}
        <h2>Update Blog</h2>
        <p class="text-secondary">Update informations and publish your blog.</p>
        <form method="post" enctype="multipart/form-data">
            {{form|crispy}}
            {% csrf_token %}
            <input type="submit" class="btn btn-dark mt-3" value="Update Blog">
        </form>
        {% else %}
        <h2>Sorry!</h2>
        <p class="text-secondary">You don't have permission to edit this blog!</p>
        {% endif %}
    </div>
</div>
{% endblock  %}

templates/app_blog/my_blogs.html
{% extends 'base.html' %}
{% block title_block %}{{user.first_name|default:"User"}}' Blogs{% endblock  %}
{% load custom_filters %}
{% load static %}
{% block body_block %}
<main class="blog-grid-page">
    <div class="container">
        <p class='lead'>{{user.first_name|default:"User"}}' Blogs</p>
        <div class="row mt-2">
            {% for blog in user.blog_author.all %}
            <div class="col-md-4 mb-4">
                <div class="card" style="height:355px">
                    <div class="overflow-hidden">
                        <a href="{% url 'app_blog:blog' slug=blog.slug %}">
                        <img class="img-fluid"
                            {% if blog.blog_image == "" %}
                                src="{% static '/images/empty.jpg' %}"
                            {% else %}
                                src="/media/{{blog.image}}"
                            {% endif %} 
                        alt=""></a>
                    </div>
                    <div class="px-3 py-1">
                        <p class="d-flex justify-content-between mb-1 text-secondary">
                            <span><i class="bi bi-calendar3"></i> {{blog.published|date}}</span>
                            <span><i class="bi bi-person-circle"></i> {{blog.author}}</span>
                        </p>
                        <h5>{{blog.title|value_range:60}}</h5>
                        <p class="mb-0">{{blog.content|value_range:85}}</p>
                    </div>
                    <div class="card-footer d-flex justify-content-between">
                        <a href="{% url 'app_blog:update' pk=blog.pk %}" class="btn btn-warning">Edit Blog Content</a>
                        <a href="{% url 'app_blog:delete' pk=blog.pk %}" class="btn btn-danger">Delete Blog</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</main>

{% endblock  %}

templates/app_blog/single_blog.html
{% extends 'base.html' %}
{% block title_block %}{{blog.title}}{% endblock  %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_block %}
<main class="blog-post-single">
    <div class="container">
        <div class="row mt-2">
            <div class="col-md-8">
                <div class="mb-1 overflow-hidden rounded border" style="max-height:300px">
                    <img class="img-fluid align-middle w-100"
                            {% if blog.blog_image == "" %}
                                src="{% static '/images/empty.jpg' %}"
                            {% else %}
                                src="/media/{{blog.image}}"
                            {% endif %} 
                        alt="">
                </div>
                <p class="mx-2 text-secondary">
                    <i class="bi bi-pencil-square"></i>
                    Posted by <b>@/{{blog.author}}</b> at {{blog.published}}.
                    Last edited at {{blog.edited}}.</p>
                <div class="post-content">
                    <h4 class="fw-bold">{{blog.title}}</h4>
                    <p class="lead">{{blog.sub_title}}</p>
                    <p style="text-align:justify">{{blog.content|linebreaks}}</p>
                </div>
                
                {% if user.is_authenticated %}   
                <form method="post" class="d-flex my-3">
                    {{comment_form|crispy}}
                    {% csrf_token %}
                    <button class="btn btn-dark me-2" type="submit"><i class="bi bi-chat-dots"></i> Comment</button>
                    {% if liked %}
                    <a class="btn btn-warning" href="{% url 'app_blog:dislike' pk=blog.pk %}">
                    <i class="bi bi-hand-thumbs-down"></i> Dislike</a>
                    {% else %}
                    <a class="btn btn-primary" href="{% url 'app_blog:like' pk=blog.pk %}">
                    <i class="bi bi-hand-thumbs-up"></i> Like</a>
                    {% endif %}
                </form>                
                {% else %}
                    <p class="lead">
                        <a class="text-decoration-none" href="{% url 'app_login:login' %}">
                        <i class="bi bi-person-circle"></i> 
                        Login</a> to post a comment.
                    </p>
                {% endif %}

                <div class="card mb-5">
                    <div class="card-header">
                        <span>
                            <i class="bi bi-hand-thumbs-up"></i>
                            <b>{{blog.blog_like.count}}</b> Likes and
                        </span>
                        <span class="ms-2">
                            <i class="bi bi-chat-right-quote ml-2"></i>
                            <b>{{blog.blog_comment.count}}</b> Comments by other users:
                        </span>
                    </div>
                    <div class="card-body">
                        {% for comment in blog.blog_comment.all %}
                            <div class="card p-2 mb-1">
                                <div class="d-flex justify-content-between">
                                    <h5 class="m-0">
                                        {% if comment.user.first_name == "" %}
                                            {{comment.user}}
                                        {% else %}
                                        {{comment.user.first_name}} {{comment.user.last_name}}
                                        {% endif %}
                                    </h5>
                                    <p>{{comment.commented}}</p>
                                </div>
                                <p class="my-0">{{comment.comment}}</p>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="mb-3">
                    <h5>Tags</h5>
                    <div class="py-3">
                        <span class="border p-2 rounded">Design</span>
                        <span class="border p-2 rounded">Development</span>
                        <span class="border p-2 rounded">UI/UX</span>
                    </div>
                </div>
                <div class="mb-3">
                    <h5>Share</h5>
                    <div class="py-3">
                        <a class="btn btn-light me-2"><i class="bi bi-facebook"></i></a>
                        <a class="btn btn-light me-2"><i class="bi bi-twitter"></i></a>
                        <a class="btn btn-light me-2"><i class="bi bi-discord"></i></a>
                        <a class="btn btn-light me-2"><i class="bi bi-telegram"></i></a>
                    </div>
                </div>
                <div class="">
                    <h5 class="">Categories</h5>
                    <div class="card" style="width: 18rem;">
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">An item</li>
                            <li class="list-group-item">A second item</li>
                            <li class="list-group-item">A third item</li>
                            <li class="list-group-item">An item</li>
                            <li class="list-group-item">A second item</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>
{% endblock  %}